import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  evolutionContainer: {
    alignItems: 'center',
    marginVertical: 16,
    width: '100%',
  },
  arrowContainer: {
    alignItems: 'center',
    marginVertical: 20,
    position: 'relative',
  },
  arrowLine: {
    width: 2,
    height: 20,
    backgroundColor: '#E5E7EB',
  },
  arrowCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#3B82F6',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    marginVertical: 8,
  },
  arrowText: {
    fontSize: 18,
    color: '#FFFFFF',
  },
  evolutionRequirementContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginTop: 12,
  },
  evolutionRequirement: {
    fontSize: 13,
    color: '#374151',
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  pokemonContainer: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    margin: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    minWidth: 160,
    position: 'relative',
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  pokemonImageContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#F8F9FA',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  pokemonImage: {
    width: 90,
    height: 90,
    resizeMode: 'contain',
  },
  placeholderImage: {
    backgroundColor: '#E5E7EB',
    borderRadius: 45,
    justifyContent: 'center',
    alignItems: 'center',
    width: 90,
    height: 90,
  },
  placeholderText: {
    fontSize: 32,
    opacity: 0.5,
  },
  pokemonInfoContainer: {
    alignItems: 'center',
    width: '100%',
  },
  pokemonName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1F2937',
    textTransform: 'capitalize',
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  pokemonId: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '600',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    letterSpacing: 0.5,
  },
  interactionIndicator: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
    opacity: 0.8,
  },
  placeholderName: {
    width: 80,
    height: 16,
    backgroundColor: '#E5E7EB',
    borderRadius: 8,
    marginBottom: 8,
  },
  placeholderId: {
    width: 50,
    height: 12,
    backgroundColor: '#E5E7EB',
    borderRadius: 6,
  },
});